<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>7b383626-8437-405a-923b-0bf666cdecaa</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MicroservicesProject.Telemetry.Ingestor\MicroservicesProject.Telemetry.Ingestor.csproj" />
    </ItemGroup>

</Project>
